/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "argonauts": {
    "base": "argonauts",
    "width": 800,
    "height": 532,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1920,
    "height": 762,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 1920,
    "height": 762,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1920,
    "height": 1277,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1279,
    "fallbackWidth": 1920,
    "fallbackHeight": 1279,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 800,
    "height": 513,
    "fallbackWidth": 800,
    "fallbackHeight": 513,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1920,
    "height": 2718,
    "fallbackWidth": 1920,
    "fallbackHeight": 2718,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1920,
    "height": 2718,
    "fallbackWidth": 1920,
    "fallbackHeight": 2718,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 800,
    "height": 532,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "iolcus": {
    "base": "iolcus",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "meteora": {
    "base": "meteora",
    "width": 800,
    "height": 318,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 1920,
    "height": 762,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1230,
    "fallbackWidth": 1920,
    "fallbackHeight": 1230,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "pagasetic": {
    "base": "pagasetic",
    "width": 1920,
    "height": 762,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "pelion": {
    "base": "pelion",
    "width": 800,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 1920,
    "height": 1277,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "tsipouro": {
    "base": "tsipouro",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "viewpoints": {
    "base": "viewpoints",
    "width": 800,
    "height": 318,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "volos-waterfront": {
    "base": "volos-waterfront",
    "width": 800,
    "height": 318,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 800,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "waterfront": {
    "base": "waterfront",
    "width": 800,
    "height": 318,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 800,
    "height": 1070,
    "fallbackWidth": 800,
    "fallbackHeight": 1070,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
